apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ufw6f12dx-python-gitops
  description: This is GitOps manifest for ufw6f12dx-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ufw6f12dx-python
    backstage.io/kubernetes-id: ufw6f12dx-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ufw6f12dx-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ufw6f12dx-python
