apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ufw6f12dx-python
  janus-idp.io/tekton: ufw6f12dx-python
  backstage.io/kubernetes-id: ufw6f12dx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ufw6f12dx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
