apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ufw6f12dx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ufw6f12dx-python 
  name: ufw6f12dx-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ufw6f12dx-python
    weight: 100 
