apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ufw6f12dx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ufw6f12dx-python 
  name: ufw6f12dx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ufw6f12dx-python 
